#ifndef GUARD_CONST_PERSONS_H
#define GUARD_CONST_PERSONS_H

enum {
    PERSON_ANIM_NONE,
    PERSON_ANIM_DUMMY01,
    PERSON_ANIM_PHOENIX,
    PERSON_ANIM_DUMMY03,
    PERSON_ANIM_MAYA,
    PERSON_ANIM_SUMMONED_MIA,
    PERSON_ANIM_DUMMY06,
    PERSON_ANIM_MIA,
    PERSON_ANIM_JUDGE,
    PERSON_ANIM_EDGEWORTH,
    PERSON_ANIM_WINSTON_PAYNE,
    PERSON_ANIM_DUMMY11,
    PERSON_ANIM_MARVIN_GROSSBERG,
    PERSON_ANIM_DUMMY13,
    PERSON_ANIM_DUMMY14,
    PERSON_ANIM_DUMMY15,
    PERSON_ANIM_PENNY_NICHOLS,
    PERSON_ANIM_WENDY_OLDBAG,
    PERSON_ANIM_SAL_MANELLA,
    PERSON_ANIM_DUMMY19,
    PERSON_ANIM_GUMSHOE,
    PERSON_ANIM_REDD_WHITE,
    PERSON_ANIM_APRIL_MAY,
    PERSON_ANIM_BELLBOY,
    PERSON_ANIM_DEE_VASQUEZ,
    PERSON_ANIM_LARRY_BUTZ,
    PERSON_ANIM_FRANK_SAWHIT,
    PERSON_ANIM_WILL_POWERS,
    PERSON_ANIM_CODY_HACKINS,
    PERSON_ANIM_BUSTUP_PHOENIX,
    PERSON_ANIM_BUSTUP_EDGEWORTH,
    PERSON_ANIM_LOTTA_HART,
    PERSON_ANIM_YANNI_YOGI,
    PERSON_ANIM_MANFRED_VONKARMA,
    PERSON_ANIM_POLLY
};

#endif//GUARD_CONST_PERSONS_H