#ifndef GUARD_CONST_PROCESS_H
#define GUARD_CONST_PROCESS_H

enum Process {
    CAPCOM_LOGO_PROCESS,
    TITLE_SCREEN_PROCESS,
    GAME_OVER_PROCESS,
    COURT_PROCESS,
    INVESTIGATION_PROCESS,
    TESTIMONY_PROCESS,
    QUESTIONING_PROCESS,
    COURT_RECORD_PROCESS,
    EVIDENCE_ADDED_PROCESS,
    VERDICT_PROCESS,
    SAVE_GAME_PROCESS,
    EPISODE_CLEAR_PROCESS,
    EPISODE_SELECT_PROCESS,
    CONTINUE_SAVE_PROCESS,
    CLEAR_SAVE_PROCESS,
};

enum CourtProcessStates {
    COURT_INIT,
    COURT_MAIN,
    COURT_EXIT,
};

enum InvestigationProcessStates {
    INVESTIGATION_INIT,
    INVESTIGATION_MAIN,
    INVESTIGATION_EXIT,
    INVESTIGATION_BG_SCROLL_WAIT,
    INVESTIGATION_TEXTBOX_SLIDE_WAIT,
    INVESTIGATION_ROOM_INIT,
    INVESTIGATION_INSPECT,
    INVESTIGATION_MOVE,
    INVESTIGATION_TALK,
    INVESTIGATION_PRESENT,
};

enum TestimonyProcessStates {
    TESTIMONY_INIT,
    TESTIMONY_MAIN,
    TESTIMONY_EXIT,
    TESTIMONY_ANIM,
};

enum QuestioningProcessStates {
    QUESTIONING_INIT,
    QUESTIONING_MAIN,
    QUESTIONING_EXIT,
    QUESTIONING_ANIM,
    QUESTIONING_HOLD_IT,
    QUESTIONING_OBJECTION,
};

enum CourtRecordProcessStates {
    RECORD_INIT,
    RECORD_MAIN,
    RECORD_EXIT,
    RECORD_CHANGE_STATE,
    RECORD_CHANGE_RECORD,
    RECORD_DETAIL_SUBMENU,
    RECORD_LOAD_GFX_CHANGE_STATE,
    RECORD_TAKE_THAT_SPECIAL,
};

enum EvidenceAddedProcessStates {
    EVIDENCE_ADD_INIT,
    EVIDENCE_ADD_MAIN,
    EVIDENCE_ADD_EXIT,
};

enum VerdictProcessStates {
    VERDICT_SHRINK_KANJI1,
    VERDICT_WAIT_INIT_KANJI2,
    VERDICT_SHRINK_KANJI2,
    VERDICT_WAIT,
    VERDICT_GROW_KANJI,
    VERDICT_INIT_CONFETTI,
    VERDICT_DRAW_CONFETTI,
    VERDICT_ANIMATE_CONFETTI,
    VERDICT_NOTGUILTY_EXIT
};

#endif//GUARD_CONST_PROCESS_H