#ifndef GUARD_CONST_PROCESS_H
#define GUARD_CONST_PROCESS_H

enum VerdictProcessStates {
    VERDICT_STATE_SHRINK_KANJI1,
    VERDICT_STATE_WAIT_INIT_KANJI2,
    VERDICT_STATE_SHRINK_KANJI2,
    VERDICT_STATE_WAIT,
    VERDICT_STATE_GROW_KANJI,
    VERDICT_STATE_INIT_CONFETTI,
    VERDICT_STATE_DRAW_CONFETTI,
    VERDICT_STATE_ANIMATE_CONFETTI,
    VERDICT_STATE_NOTGUILTY_EXIT
};

#endif//GUARD_CONST_PROCESS_H