#ifndef GUARD_CONST_PROCESS_H
#define GUARD_CONST_PROCESS_H

enum VerdictProcessStates {
    VERDICT_STATE_INIT,
    VERDICT_STATE_INIT_GFX,
    VERDICT_STATE_NEXT_ANIM,
    VERDICT_STATE_MAIN_ANIM,
    VERDICT_STATE_FINISH_ANIM,
    VERDICT_STATE_WAIT,
    VERDICT_STATE_VERDICT_CLEANUP,
    VERDICT_STATE_GROW_KANJI,
    VERDICT_STATE_INIT_CONFETTI,
    VERDICT_STATE_DRAW_CONFETTI,
    VERDICT_STATE_ANIMATE_CONFETTI,
    VERDICT_STATE_NOTGUILTY_EXIT
};

#endif//GUARD_CONST_PROCESS_H