#ifndef GUARD_CONST_SCRIPT_H
#define GUARD_CONST_SCRIPT_H

#define SCRIPT_FULLSCREEN 0x4
#define SCRIPT_LOOP 0x8
#define SCRIPT_SPOTSELECT_MOVE_TO_START 0x80
#define SCRIPT_SPOTSELECT_INPUT 0x100
#define SCRIPT_SPOTSELECT_PLAY_SPAWN_SOUND 0x200
#define SCRIPT_SPOTSELECT_SELECTION_MADE 0x400

#endif //GUARD_SCRIPT_H
