#ifndef GUARD_CONST_SOUND_H
#define GUARD_CONST_SOUND_H

#define SOUND_STATUS_BGM_STOPPED (1 << 0)
#define SOUND_STATUS_BGM_PAUSED (1 << 1)
#define SOUND_STATUS_BGM_PLAYING (1 << 2)
#define SOUND_STATUS_BGM_FADING (1 << 3)
#define SOUND_STATUS_BGM_FADING_OUT (1 << 4)

#endif//GUARD_CONST_SOUND_H
